package recyclapp.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.LinkedList;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class InterfaceOutils extends JPanel {

    private boolean moveTools;
    private int idTools;
    private int[][] coordImage = new int[4][2];
    private int[] coord = new int[2];
    private LinkedList<Image> images = new LinkedList<>();
    private int sizeImage = 70;

    public static final int ID_NOTHING = -1;
    public static final int ID_TOOL_STATION = 0;
    public static final int ID_TOOL_ENTREE = 1;
    public static final int ID_TOOL_SORTIE = 2;
    public static final int ID_TOOL_ARC = 3;
    public static final int ID_TOOL_JONCTION = 4;

    public InterfaceOutils() {
        //initComponents();
        
        this.idTools = ID_NOTHING;
        this.moveTools = false;
        this.setLayout(new java.awt.BorderLayout());
        coord = new int[2];
        coord[0] = 0;
        coord[1] = 0;
        images = new LinkedList<>();
        coordImage = new int[4][2];
        images.add(ID_TOOL_STATION, getToolkit().getImage("resources/Station.png"));
        images.add(ID_TOOL_ENTREE, getToolkit().getImage("resources/Entree.png"));
        images.add(ID_TOOL_SORTIE, getToolkit().getImage("resources/Sortie.png"));
        images.add(ID_TOOL_ARC, getToolkit().getImage("resources/Arc.png"));
        sizeImage = 70;

        this.setBackground(new Color(164, 183, 145));
        this.setPreferredSize(new java.awt.Dimension(150, 588));
        this.setLayout(new java.awt.BorderLayout());
    }

    /**
     * *
     * summary : Retourne l'ID de l'élément aux coordonées indiquées.
     *
     * @param x
     * @param y
     * @return
     */
    private int searchIdTool(int x, int y) {
        int result = ID_NOTHING;

        for (int imageId = 0; imageId < images.size(); imageId++) {
            if (x >= coordImage[imageId][0] && x <= coordImage[imageId][0] + sizeImage
                    && y >= coordImage[imageId][1] && y <= coordImage[imageId][1] + sizeImage) {
                coord[0] = coordImage[imageId][0];
                coord[1] = coordImage[imageId][1];
                result = imageId;
                break;
            }
        }
        return result;
    }

    /**
     * *
     * summary : Permet de définir si l'outil aux coordonnées cliquées est
     * déplacable.
     *
     * @param x
     * @param y
     */
    public void moveTool(int x, int y) {
        this.idTools = this.searchIdTool(x, y);
        if (getIdTools() >= 0) {
            this.moveTools = true;
        } else {
            this.idTools = ID_NOTHING;
            this.moveTools = false;
        }
    }

    public int getIdTools() {
        return idTools;
    }

    public void setMoveTools(boolean isMoveable) {
        this.moveTools = isMoveable;
    }

    public void resetTools() {
        this.idTools = ID_NOTHING;
    }

    public boolean isMoveTools() {
        return moveTools;
    }

    public int getCoordWidth(int i) {
        return coordImage[i][0] + sizeImage;
    }

    public int getCoordHeigth(int i) {
        return coordImage[i][1] + sizeImage;
    }

    public Image getImages(int imageId) {
        return images.get(imageId);
    }

    public int getSizeImage() {
        return sizeImage;
    }

    @Override
    public void paintComponent(Graphics graphic) {
        super.paintComponent(graphic);
        int height = 100;

        for (int imageId = 0; imageId < images.size(); imageId++) {
            coordImage[imageId][0] = this.getWidth() / 2 - (sizeImage / 2);
            coordImage[imageId][1] = height * (imageId + 1);
            graphic.drawImage(images.get(imageId), coordImage[imageId][0], coordImage[imageId][1], sizeImage, sizeImage, this);
        }
        graphic.setColor(Color.red);
        if (this.moveTools) {
            graphic.drawRect(coord[0], coord[1], sizeImage, sizeImage);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOutils = new javax.swing.JPanel();
        jLabelOutils = new javax.swing.JLabel();
        jLabelStation = new javax.swing.JLabel();
        jLabelEntreeUsine = new javax.swing.JLabel();
        jLabelSortieUsine = new javax.swing.JLabel();
        jLabelArc = new javax.swing.JLabel();
        jLabelJonction = new javax.swing.JLabel();
        jButtonStation = new javax.swing.JButton();
        jButtonEntree = new javax.swing.JButton();
        jButtonSortie = new javax.swing.JButton();
        jButtonArc = new javax.swing.JButton();
        jButtonJonction = new javax.swing.JButton();

        jPanelOutils.setBackground(new java.awt.Color(164, 183, 145));

        jLabelOutils.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelOutils.setText("Outils");

        jLabelStation.setText("Station :");

        jLabelEntreeUsine.setText("Entrée usine :");

        jLabelSortieUsine.setText("Sortie usine :");

        jLabelArc.setText("Arc :");

        jLabelJonction.setText("Jonction :");

        jButtonStation.setText("jButton1");

        jButtonEntree.setText("jButton2");

        jButtonSortie.setText("jButton3");

        jButtonArc.setText("jButton4");

        jButtonJonction.setText("jButton5");

        javax.swing.GroupLayout jPanelOutilsLayout = new javax.swing.GroupLayout(jPanelOutils);
        jPanelOutils.setLayout(jPanelOutilsLayout);
        jPanelOutilsLayout.setHorizontalGroup(
            jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOutilsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOutilsLayout.createSequentialGroup()
                        .addComponent(jLabelJonction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonJonction))
                    .addGroup(jPanelOutilsLayout.createSequentialGroup()
                        .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelArc)
                            .addComponent(jLabelSortieUsine)
                            .addComponent(jLabelStation)
                            .addComponent(jLabelEntreeUsine))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonStation)
                                    .addComponent(jButtonEntree, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jButtonSortie, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButtonArc, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(30, 30, 30))
            .addGroup(jPanelOutilsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabelOutils)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOutilsLayout.setVerticalGroup(
            jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutilsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelOutils)
                .addGap(44, 44, 44)
                .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStation)
                    .addComponent(jButtonStation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEntreeUsine)
                    .addComponent(jButtonEntree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSortie)
                    .addComponent(jLabelSortieUsine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArc)
                    .addComponent(jButtonArc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOutilsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJonction)
                    .addComponent(jButtonJonction))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOutils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOutils, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArc;
    private javax.swing.JButton jButtonEntree;
    private javax.swing.JButton jButtonJonction;
    private javax.swing.JButton jButtonSortie;
    private javax.swing.JButton jButtonStation;
    private javax.swing.JLabel jLabelArc;
    private javax.swing.JLabel jLabelEntreeUsine;
    private javax.swing.JLabel jLabelJonction;
    private javax.swing.JLabel jLabelOutils;
    private javax.swing.JLabel jLabelSortieUsine;
    private javax.swing.JLabel jLabelStation;
    private javax.swing.JPanel jPanelOutils;
    // End of variables declaration//GEN-END:variables
}
